//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SurName { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Identification_number { get; set; }
        public string Series_passport { get; set; }
        public Nullable<int> Id_passport { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Position Position1 { get; set; }
    }
}
