//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9043
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contoso.com/books")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.contoso.com/books", IsNullable=false)]
public partial class Knife {
    
    private KnifeWeapon[] weaponField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Weapon")]
    public KnifeWeapon[] Weapon {
        get {
            return this.weaponField;
        }
        set {
            this.weaponField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contoso.com/books")]
public partial class KnifeWeapon {
    
    private KnifeWeaponVisual visualField;
    
    private decimal priceField;
    
    private string typeField;
    
    private bool handyField;
    
    private string countryField;
    
    /// <remarks/>
    public KnifeWeaponVisual Visual {
        get {
            return this.visualField;
        }
        set {
            this.visualField = value;
        }
    }
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Handy {
        get {
            return this.handyField;
        }
        set {
            this.handyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.contoso.com/books")]
public partial class KnifeWeaponVisual {
    
    private int heightField;
    
    private int widthField;
    
    private int weightField;
    
    /// <remarks/>
    public int height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public int width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public int weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}